name: Discord Alerts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para o Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          args: |
            🚀 Novo evento no repositório **${{ github.repository }}**
            🔹 Tipo de evento: **${{ github.event_name }}**
            🔹 Branch: **${{ github.ref }}**
            🔹 Autor:
