name: Discord Alerts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🚀 Novo evento no repositório **${{ github.repository }}**
            🔹 Tipo de evento: **${{ github.event_name }}**
            🔹 Branch: **${{ github.ref_name }}**
            🔹 Autor: **${{ github.actor }}**
