name: CI - Testes Automatizados

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "feature-*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar testes
      run: pytest
