name: CD - Deploy Automático

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Simular Deploy
      run: |
        echo "Iniciando processo de Deploy 🚀"
        echo "Deploy concluído com sucesso!"
